package Generator.InterfaceAdapter.display_timetable;

import CourseInfo.Section;
import Generator.UseCase.generate_timetable.TimetableDTO;

import java.util.ArrayList;


//// All timetable results generated by the use case, already converted to DTOs.(See DTO for details.)
//// Each TimeTableDTO represents one complete, valid schedule option.
//// The View should iterate through this list and display each timetable
///  The main attribute for this class is allTimeTables, which is enough for generating a timetable.
///  The other attributes is for additional features.
public class DisplayTimetableState {
    private ArrayList<String> courseCodes = new ArrayList<>();
    private ArrayList<String> courseNames = new ArrayList<>();
    private ArrayList<ArrayList<Section>> lectureSections = new ArrayList<>();
    private ArrayList<ArrayList<Section>> tutorialSections = new ArrayList<>();
    private ArrayList<ArrayList<Section>> practicalSections = new ArrayList<>();
    private ArrayList<Double> credit = new ArrayList<>();
    private ArrayList<String> sessionCode = new ArrayList<>();
    private String noCourseError;
    private ArrayList<TimetableDTO>  allTimeTables;

    public DisplayTimetableState() {
    }

    public ArrayList<String> getCourses() {
        return courseCodes;
    }
    public ArrayList<String > getCourseNames() {
        return courseNames;
    }


    public ArrayList<ArrayList<Section>> getLectureSections() {
        return lectureSections;
    }
    public ArrayList<ArrayList<Section>> getTutorialSections() {
        return tutorialSections;
    }
    public ArrayList<ArrayList<Section>> getPracticalSections() {
        return practicalSections;
    }
    public ArrayList<Double> getCredit() {
        return credit;
    }
    public ArrayList<String> getSessionCode() {
        return sessionCode;
    }
    public String getNoCourseError() {
        return noCourseError;
    }
    public ArrayList<TimetableDTO> getAllTimeTables() {
        return allTimeTables;
    }
    public void setCourses(ArrayList<String> courses) {
        this.courseCodes = courses;
    }
    public void setCourseNames(ArrayList<String> courseNames) {
        this.courseNames = courseNames;
    }
    public void setLectureSections(ArrayList<ArrayList<Section>> lectureSections) {
        this.lectureSections = lectureSections;
    }
    public void setTutorialSections(ArrayList<ArrayList<Section>> tutorialSections) {
        this.tutorialSections = tutorialSections;
    }
    public void setPracticalSections(ArrayList<ArrayList<Section>> practicalSections) {
        this.practicalSections = practicalSections;
    }
    public void setCredit(ArrayList<Double> credit) {
        this.credit = credit;
    }
    public void setSessionCode(ArrayList<String> sessionCode) {
        this.sessionCode = sessionCode;
    }
    public void setNoCourseError(String noCourseError) {
        this.noCourseError = noCourseError;
    }
    public void setAllTimeTables (ArrayList<TimetableDTO>  allTimeTables) {
        this.allTimeTables = allTimeTables;
    }

    public void addCourseName(String courseName) {
        this.courseNames.add(courseName);
    }
    public void addCourseCode(String courseCode) {
        this.courseCodes.add(courseCode);
    }
    public void addLectureSection(ArrayList<Section> section) {
        this.lectureSections.add(section);
    }
    public void addTutorialSection(ArrayList<Section> section) {
        this.tutorialSections.add(section);
    }
    public void addPracticalSection(ArrayList<Section> section) {
        this.practicalSections.add(section);
    }
    public void addCredit(Double credit) {
        this.credit.add(credit);
    }
    public void addSessionCode(String sessionCode) {
        this.sessionCode.add(sessionCode);
    }
    public void removeCourse(String courseCode) {
        int index = this.courseCodes.indexOf(courseCode);
        this.courseCodes.remove(index);
        this.courseNames.remove(index);
        this.lectureSections.remove(index);
        this.tutorialSections.remove(index);
        this.practicalSections.remove(index);
        this.credit.remove(index);
        this.sessionCode.remove(index);
    }
}


