package Generator.InterfaceAdapter.display_timetable;

import Generator.UseCase.generate_timetable.TimetableDTO;

import java.util.ArrayList;


//// All timetable results generated by the use case, already converted to DTOs.(See DTO for details.)
//// Each TimeTableDTO represents one complete, valid schedule option.
//// The View should iterate through this list and display each timetable
///  The main attribute for this class is allTimeTables, which is enough for generating a timetable.
///  The other attributes is for additional features.
public class DisplayTimetableState {
    private ArrayList<String> courseCodes = new ArrayList<>();
    private ArrayList<String> courseNames = new ArrayList<>();
    private ArrayList<Double> credit = new ArrayList<>();
    private String noCourseError;
    private ArrayList<TimetableDTO> fallTimetables;
    private ArrayList<TimetableDTO> winterTimetables;
    private int fallIndex = 0;
    private int winterIndex = 0;

    public DisplayTimetableState() {
    }

    public ArrayList<String> getCourses() {
        return courseCodes;
    }
    public ArrayList<String > getCourseNames() {
        return courseNames;
    }
    public ArrayList<Double> getCredit() {
        return credit;
    }
    public String getNoCourseError() {
        return noCourseError;
    }
    public ArrayList<TimetableDTO> getFallTimetables() {
        return fallTimetables;
    }
    public ArrayList<TimetableDTO> getWinterTimetables() {
        return winterTimetables;
    }

    public void setCourses(ArrayList<String> courses) {
        this.courseCodes = courses;
    }
    public void setCourseNames(ArrayList<String> courseNames) {
        this.courseNames = courseNames;
    }
    public void setCredit(ArrayList<Double> credit) {
        this.credit = credit;
    }
    public void setNoCourseError(String noCourseError) {
        this.noCourseError = noCourseError;
    }
    public void setFallTimetables(ArrayList<TimetableDTO> fallTimetables) {
        this.fallTimetables = fallTimetables;
    }
    public void setWinterTimetables(ArrayList<TimetableDTO> winterTimetables) {
        this.winterTimetables = winterTimetables;
    }

    public void addCourseName(String courseName) {
        this.courseNames.add(courseName);
    }
    public void addCourseCode(String courseCode) {
        this.courseCodes.add(courseCode);
    }
    public void addCredit(Double credit) {
        this.credit.add(credit);
    }

    public void removeCourse(String courseCode) {
        int index = this.courseCodes.indexOf(courseCode);
        this.courseCodes.remove(index);
        this.courseNames.remove(index);
        this.credit.remove(index);
    }

    /**
     * currently just goes to the next timetable in the arraylist
     */
    public void changeTimetableIndex() {
        fallIndex++;
        winterIndex++;

        if (fallIndex >= fallTimetables.size()) {
            fallIndex = 0;
        }
        if (winterIndex >= winterTimetables.size()) {
            winterIndex = 0;
        }
    }

    public void resetTimetableIndex() {
        fallIndex = 0;
        winterIndex = 0;
    }

    public int getFallIndex() {
        return fallIndex;
    }

    public int getWinterIndex() {
        return winterIndex;
    }
}


